// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _top_module_HH_
#define _top_module_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "top_module_fmul_3bkb.h"
#include "top_module_sitofpcud.h"
#include "top_module_mac_mudEe.h"

namespace ap_rtl {

struct top_module : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<14> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<8> > output_r_d0;
    sc_out< sc_lv<14> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<8> > input_r_q0;
    sc_out< sc_lv<5> > kernel_V_address0;
    sc_out< sc_logic > kernel_V_ce0;
    sc_in< sc_lv<4> > kernel_V_q0;
    sc_in< sc_lv<32> > alpha_kernel;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    top_module(sc_module_name name);
    SC_HAS_PROCESS(top_module);

    ~top_module();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    top_module_fmul_3bkb<1,4,32,32,32>* top_module_fmul_3bkb_U1;
    top_module_sitofpcud<1,6,32,32>* top_module_sitofpcud_U2;
    top_module_mac_mudEe<1,1,4,8,32,32>* top_module_mac_mudEe_U3;
    sc_signal< sc_lv<17> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > zext_ln16_fu_219_p1;
    sc_signal< sc_lv<8> > zext_ln16_reg_529;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<7> > i_fu_229_p2;
    sc_signal< sc_lv<7> > i_reg_537;
    sc_signal< sc_lv<15> > sub_ln32_fu_259_p2;
    sc_signal< sc_lv<15> > sub_ln32_reg_542;
    sc_signal< sc_lv<1> > icmp_ln11_fu_223_p2;
    sc_signal< sc_lv<8> > zext_ln17_fu_265_p1;
    sc_signal< sc_lv<8> > zext_ln17_reg_547;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<7> > j_fu_275_p2;
    sc_signal< sc_lv<7> > j_reg_555;
    sc_signal< sc_lv<3> > k_fu_287_p2;
    sc_signal< sc_lv<3> > k_reg_563;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<6> > add_ln215_fu_309_p2;
    sc_signal< sc_lv<6> > add_ln215_reg_568;
    sc_signal< sc_lv<1> > icmp_ln20_fu_281_p2;
    sc_signal< sc_lv<16> > zext_ln22_fu_323_p1;
    sc_signal< sc_lv<16> > zext_ln22_reg_573;
    sc_signal< sc_lv<15> > add_ln32_fu_331_p2;
    sc_signal< sc_lv<15> > add_ln32_reg_578;
    sc_signal< sc_lv<3> > l_fu_342_p2;
    sc_signal< sc_lv<3> > l_reg_586;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln22_fu_336_p2;
    sc_signal< sc_lv<8> > y_2_fu_376_p2;
    sc_signal< sc_lv<8> > y_2_reg_601;
    sc_signal< sc_lv<8> > x_1_fu_382_p2;
    sc_signal< sc_lv<8> > input_load_reg_611;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<4> > kernel_V_load_reg_616;
    sc_signal< sc_lv<32> > grp_fu_516_p3;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > grp_fu_215_p1;
    sc_signal< sc_lv<32> > tmp_reg_626;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<23> > tmp_V_1_fu_408_p1;
    sc_signal< sc_lv<23> > tmp_V_1_reg_631;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<9> > add_ln339_fu_416_p2;
    sc_signal< sc_lv<9> > add_ln339_reg_636;
    sc_signal< sc_lv<1> > isNeg_reg_641;
    sc_signal< sc_lv<8> > sub_ln1311_fu_430_p2;
    sc_signal< sc_lv<8> > sub_ln1311_reg_647;
    sc_signal< sc_lv<7> > x_reg_123;
    sc_signal< sc_lv<1> > icmp_ln13_fu_269_p2;
    sc_signal< sc_lv<7> > y_reg_134;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<32> > convolute_2_reg_146;
    sc_signal< sc_lv<8> > x_0_reg_158;
    sc_signal< sc_lv<3> > k_0_reg_168;
    sc_signal< sc_lv<32> > convolute_3_reg_179;
    sc_signal< sc_lv<8> > y_1_reg_191;
    sc_signal< sc_lv<3> > l_0_reg_200;
    sc_signal< sc_lv<64> > zext_ln215_3_fu_357_p1;
    sc_signal< sc_lv<64> > zext_ln26_1_fu_371_p1;
    sc_signal< sc_lv<64> > sext_ln32_fu_512_p1;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<14> > tmp_1_fu_235_p3;
    sc_signal< sc_lv<9> > tmp_2_fu_247_p3;
    sc_signal< sc_lv<15> > zext_ln32_fu_243_p1;
    sc_signal< sc_lv<15> > zext_ln32_1_fu_255_p1;
    sc_signal< sc_lv<5> > tmp_5_fu_297_p3;
    sc_signal< sc_lv<6> > zext_ln215_fu_293_p1;
    sc_signal< sc_lv<6> > zext_ln215_1_fu_305_p1;
    sc_signal< sc_lv<15> > tmp_6_fu_315_p3;
    sc_signal< sc_lv<15> > zext_ln32_2_fu_327_p1;
    sc_signal< sc_lv<6> > zext_ln215_2_fu_348_p1;
    sc_signal< sc_lv<6> > add_ln215_1_fu_352_p2;
    sc_signal< sc_lv<16> > zext_ln26_fu_362_p1;
    sc_signal< sc_lv<16> > add_ln26_fu_366_p2;
    sc_signal< sc_lv<32> > grp_fu_211_p2;
    sc_signal< sc_lv<32> > p_Val2_s_fu_394_p1;
    sc_signal< sc_lv<8> > tmp_V_fu_398_p4;
    sc_signal< sc_lv<9> > zext_ln339_fu_412_p1;
    sc_signal< sc_lv<25> > mantissa_V_fu_436_p4;
    sc_signal< sc_lv<9> > sext_ln1311_fu_449_p1;
    sc_signal< sc_lv<9> > ush_fu_452_p3;
    sc_signal< sc_lv<32> > sext_ln1311_1_fu_458_p1;
    sc_signal< sc_lv<25> > sext_ln1311_2_fu_462_p1;
    sc_signal< sc_lv<55> > zext_ln682_fu_445_p1;
    sc_signal< sc_lv<55> > zext_ln1287_fu_466_p1;
    sc_signal< sc_lv<25> > r_V_fu_470_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_482_p3;
    sc_signal< sc_lv<55> > r_V_1_fu_476_p2;
    sc_signal< sc_lv<8> > zext_ln662_fu_490_p1;
    sc_signal< sc_lv<8> > tmp_4_fu_494_p4;
    sc_signal< sc_lv<8> > grp_fu_516_p1;
    sc_signal< sc_lv<17> > ap_NS_fsm;
    sc_signal< sc_lv<12> > grp_fu_516_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<17> ap_ST_fsm_state1;
    static const sc_lv<17> ap_ST_fsm_state2;
    static const sc_lv<17> ap_ST_fsm_state3;
    static const sc_lv<17> ap_ST_fsm_state4;
    static const sc_lv<17> ap_ST_fsm_state5;
    static const sc_lv<17> ap_ST_fsm_state6;
    static const sc_lv<17> ap_ST_fsm_state7;
    static const sc_lv<17> ap_ST_fsm_state8;
    static const sc_lv<17> ap_ST_fsm_state9;
    static const sc_lv<17> ap_ST_fsm_state10;
    static const sc_lv<17> ap_ST_fsm_state11;
    static const sc_lv<17> ap_ST_fsm_state12;
    static const sc_lv<17> ap_ST_fsm_state13;
    static const sc_lv<17> ap_ST_fsm_state14;
    static const sc_lv<17> ap_ST_fsm_state15;
    static const sc_lv<17> ap_ST_fsm_state16;
    static const sc_lv<17> ap_ST_fsm_state17;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<7> ap_const_lv7_7C;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<9> ap_const_lv9_181;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<8> ap_const_lv8_7F;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1F;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_add_ln215_1_fu_352_p2();
    void thread_add_ln215_fu_309_p2();
    void thread_add_ln26_fu_366_p2();
    void thread_add_ln32_fu_331_p2();
    void thread_add_ln339_fu_416_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_516_p1();
    void thread_grp_fu_516_p10();
    void thread_i_fu_229_p2();
    void thread_icmp_ln11_fu_223_p2();
    void thread_icmp_ln13_fu_269_p2();
    void thread_icmp_ln20_fu_281_p2();
    void thread_icmp_ln22_fu_336_p2();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_j_fu_275_p2();
    void thread_k_fu_287_p2();
    void thread_kernel_V_address0();
    void thread_kernel_V_ce0();
    void thread_l_fu_342_p2();
    void thread_mantissa_V_fu_436_p4();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_p_Val2_s_fu_394_p1();
    void thread_r_V_1_fu_476_p2();
    void thread_r_V_fu_470_p2();
    void thread_sext_ln1311_1_fu_458_p1();
    void thread_sext_ln1311_2_fu_462_p1();
    void thread_sext_ln1311_fu_449_p1();
    void thread_sext_ln32_fu_512_p1();
    void thread_sub_ln1311_fu_430_p2();
    void thread_sub_ln32_fu_259_p2();
    void thread_tmp_1_fu_235_p3();
    void thread_tmp_2_fu_247_p3();
    void thread_tmp_4_fu_494_p4();
    void thread_tmp_5_fu_297_p3();
    void thread_tmp_6_fu_315_p3();
    void thread_tmp_8_fu_482_p3();
    void thread_tmp_V_1_fu_408_p1();
    void thread_tmp_V_fu_398_p4();
    void thread_ush_fu_452_p3();
    void thread_x_1_fu_382_p2();
    void thread_y_2_fu_376_p2();
    void thread_zext_ln1287_fu_466_p1();
    void thread_zext_ln16_fu_219_p1();
    void thread_zext_ln17_fu_265_p1();
    void thread_zext_ln215_1_fu_305_p1();
    void thread_zext_ln215_2_fu_348_p1();
    void thread_zext_ln215_3_fu_357_p1();
    void thread_zext_ln215_fu_293_p1();
    void thread_zext_ln22_fu_323_p1();
    void thread_zext_ln26_1_fu_371_p1();
    void thread_zext_ln26_fu_362_p1();
    void thread_zext_ln32_1_fu_255_p1();
    void thread_zext_ln32_2_fu_327_p1();
    void thread_zext_ln32_fu_243_p1();
    void thread_zext_ln339_fu_412_p1();
    void thread_zext_ln662_fu_490_p1();
    void thread_zext_ln682_fu_445_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
